from decouple import config, Csv


SOURCE_CHANNEL_PROFIT_HUNTER = int(config("SOURCE_CHANNEL_PROFIT_HUNTER"))
DESTINATION_CHANNELS_PROFIT_HUNTER = int(config("DESTINATION_CHANNELS_PROFIT_HUNTER"))

SOURCE_CHANNEL_LONG_SHORT_BITMEX_HIDDEN = config("SOURCE_CHANNEL_LONG_SHORT_BITMEX_HIDDEN", cast=Csv(int))
DESTINATION_CHANNEL_LONG_SHORT_BITMEX_HIDDEN = config("DESTINATION_CHANNEL_LONG_SHORT_BITMEX_HIDDEN", cast=Csv(int))
DESTINATION_CHANNEL_LONG_SHORT_BITMEX_HIDDEN_FTX = config("DESTINATION_CHANNEL_LONG_SHORT_BITMEX_HIDDEN_FTX", cast=Csv(int))

LEVISSIGNALS_SOURCE_CHANNEL = config('LEVISSIGNALS_SOURCE_CHANNEL')
LEVISSIGNALS_DESTINATION_CHANNEL = config('LEVISSIGNALS_DESTINATION_CHANNEL', cast=Csv(int))
LEVISSIGNALS_DESTINATION_CHANNEL_FTX = config('LEVISSIGNALS_DESTINATION_CHANNEL_FTX')
LEVISSIGNALS_DESTINATION_CHANNEL_BINANCE = config('LEVISSIGNALS_DESTINATION_CHANNEL_BINANCE')

SPECIAL_LEV_COIN_LIST = config('SPECIAL_LEV_COIN_LIST')

SOURCE_CHANNEL_HIPPO_TO_MONTHLY = config("SOURCE_CHANNEL_HIPPO_TO_MONTHLY", cast=Csv(int))
DESTINATION_CHANNEL_HIPPO_TO_MONTHLY = config("DESTINATION_CHANNEL_HIPPO_TO_MONTHLY", cast=Csv(int))

SOURCE_CHANNEL_HIPPO = config("SOURCE_CHANNEL_HIPPO", cast=Csv(int))
DESTINATION_HIPPO = config("DESTINATION_HIPPO", cast=Csv(int))

API_ID = int(config("API_ID"))
API_HASH = config("API_HASH")
